HW 4 540

1. Generate random 100 MVN data, p=20. 

The covariance matrix should be positive semi- definite symmetric matrix.

(1) Calculate sample covariance matrix.

(2) Find out the first three principal components.

(3) Calcuate the proportions of the variability of data that can be explained by the first K

principal components and find the value of K that it reaches to 99% of the variability.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st
from scipy.stats import *
%matplotlib inline
# np.random.seed(42)

In [4]:
a = np.array([[-1,1,5],[4,3,-2]])
b = np.array([[1,-1],[0,2],[-3,6]])

In [5]:
a@b

array([[-16,  33],
       [ 10, -10]])

In [6]:
np.matmul(a, b)

array([[-16,  33],
       [ 10, -10]])

In [9]:
a.T

array([[ 1,  0, -3],
       [-1,  2,  6]])

In [11]:
b.T

array([[ 1,  0, -3],
       [-1,  2,  6]])

2. Generate $Y$ values using the following regression functions: 

$Y=5+2 X_{1}+5 X_{3}+$ $3 X_{19}+\epsilon$ 
for the generated X matrix in #1

 (1) Estimate the regression line using the least square method and find out the predicted values, residuals for each observation and the mean square errors.

(2) Estimate the regression line using the least square method based on the first 5 principal components and find out the predicted values, residuals for each observation and the mean square errors.

(3) Compare the results in (1) and (2).