HW 3 of Computational methods 540

Review of basic statistics:MVN

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
import matplotlib as mpl
import scipy.stats as st
from scipy.stats import *

In [7]:
N = 2000
d = 3
x = np.random.normal(size=(d, N))
mu = np.random.random(3)
C = np.random.random((3, 3))
cov3 = C @ C.T # positive semi-definite

In [8]:
mu , cov3

(array([0.0964856 , 0.01082985, 0.64966798]),
 array([[0.69498649, 0.49669505, 0.40650307],
        [0.49669505, 0.53387075, 0.61720953],
        [0.40650307, 0.61720953, 0.95863517]]))

In [11]:
eigv3 = np.linalg.eigvals(cov3)
L = np.linalg.cholesky(cov3)

In [12]:
eigv3, L

(array([1.76373169, 0.40196748, 0.02179326]),
 array([[0.8336585 , 0.        , 0.        ],
        [0.59580159, 0.42295534, 0.        ],
        [0.48761342, 0.77239521, 0.35252513]]))

array([[ 1.        , -0.90866959, -0.93974699],
       [-0.90866959,  1.        ,  0.996656  ],
       [-0.93974699,  0.996656  ,  1.        ]])

In [2]:
# x = np.linspace(0, 5, 10)
# mean = np.array([5,1,2])
# cov = np.array([[20,11,-2], [11,2,8],[-2,8,7]])
# mvn3 = multivariate_normal(x,mean,cov)

In [1]:
# d = 3
# mean = np.matrix([5,1,2])
# cov = np.matrix([[20,11,-2], [11,2,8],[-2,8,7]])
# # eval = np.linalg.eigvals(cov)
# L = linalg.cholesky(cov)
# n = 50  # Samples to draw
# X = np.random.normal(size=(d, n))
# # Apply the transformation
# Y = L.dot(X) + mean
# eval = np.linalg.eigvals(cov)
# eval

array([-7.68816417, 25.37549149, 11.31267269])

(array([0.64103298, 0.59192331, 0.41129166]),
 array([[1.19540972, 1.30570592, 1.29346098],
        [1.30570592, 1.50171879, 1.39564807],
        [1.29346098, 1.39564807, 2.09241537]]))