HW 4 540

1. Generate random 100 MVN data, p=20. 

The covariance matrix should be positive semi- definite symmetric matrix.

(1) Calculate sample covariance matrix.

(2) Find out the first three principal components.

(3) Calcuate the proportions of the variability of data that can be explained by the first K

principal components and find the value of K that it reaches to 99% of the variability.

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st
from scipy.stats import *
from numpy import *
%matplotlib inline
np.random.seed(42)

In [25]:
# p=20
# The Multivariate  normal distribution with p =20 mean vector is mu.
# The covariance matrix is cov.
mu = np.random.uniform(-10,10,size=20)
C = np.random.random((20,20))
cov = C @ C.T # positive semi-definite

In [32]:
# pd.DataFrame(mu)

In [40]:
# pd.DataFrame(cov)

In [44]:
Ns = 100 #Generate 100 samples from x1-x20
data = np.random.multivariate_normal(mu, cov, size=Ns)
# pd.DataFrame(data)


x1 = data[:, 0]
x2 = data[:, 1]
x3 = data[:,2]
x4 = data[:,3]
x5 = data[:,4]
x6 = data[:,]
x = data[:,]
x = data[:,]
x = data[:,]
x = data[:,]
x = data[:,]
x = data[:,]
x = data[:,]
x20 = data[:,19]

In [45]:
x20

51,  3.55529393, -0.47162436,  2.51001252,  0.19159801,
        5.2990087 ,  7.24169774,  5.02390147,  1.04320753,  7.55823828,
        2.98177806,  3.66257963,  2.9750217 ,  1.56173504,  2.67196209])

In [4]:
a = np.array([[-1,1,5],[4,3,-2]])
b = np.array([[1,-1],[0,2],[-3,6]])

In [5]:
a@b

array([[-16,  33],
       [ 10, -10]])

In [6]:
np.matmul(a, b)

array([[-16,  33],
       [ 10, -10]])

In [9]:
a.T

array([[ 1,  0, -3],
       [-1,  2,  6]])

In [11]:
b.T

array([[ 1,  0, -3],
       [-1,  2,  6]])

2. Generate $Y$ values using the following regression functions: 

$Y=5+2 X_{1}+5 X_{3}+$ $3 X_{19}+\epsilon$ 
for the generated X matrix in #1

 (1) Estimate the regression line using the least square method and find out the predicted values, residuals for each observation and the mean square errors.

(2) Estimate the regression line using the least square method based on the first 5 principal components and find out the predicted values, residuals for each observation and the mean square errors.

(3) Compare the results in (1) and (2).